# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 하이브레인넷 부설연구소
email: apps@hibrain.net
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll-and-hybe" # the subpath of your site, e.g. /blog
url: "https://hibrainnet.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hibrainapps
github_username:  hibrainnet

disqus:
     shortname: hibrainappsblog

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-compose
  - jekyll-seo-tag



# pagetype = 페이징 방법 { numbering || simple }
# limit_page = 한 화면에 보여줄 페이지 수
limit_page: 5
pagetype: "numbering"

#query string에 사용할 변수명
tag_param: 'tags'
category_param: 'cate'
page_type: 'type'
post_title: 'title'
page_num: 'page'

# jekyll-patinate-v2 플러그인에서 사용하는 변수
pagination:
    enabled: true
    per_page: 1
    permalink: '/page/:num'
    limit: 0
    sort_field: "date"
    sort_reverse: true

    #카테고리, 태그 페이징 숫자에 할당될 주소 형식
    cate_link: '/category/:cname'
    tag_link: '/tags/:tname'
    tmp_page_link: '/page/'






# jekyll-patinate 플러그인에서 사용하는 변수
#paginate: 1
#paginate_path: '/page/:num/'


# hooks에서 사용하는 master 계정 변수

git:
  admin-git-email: rkgp05151@gmail.com


 




# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - vendor
  - Gemfile
  - Geffile.lock
  - LICENSE
  - README.md
  - Rakefile

#pre-push hook 변수
#githubURL=소스코드를 push할 URL
#githubBranch=소스코트를 push할 Branch
#remoteName=소스코드를 보낼 remote 이름
githubURL: git@github.com:hibrainnet/jekyll-and-hybe.git
githubBranch: source
remoteName: github


